name: Daily Naver Place Crawler

on:
  schedule:
    # 매일 오전 11:20 (KST) = 02:20 (UTC)
    - cron: '20 2 * * *'
    # 매일 오후 1:50 (KST) = 04:50 (UTC)  
    - cron: '50 4 * * *'
  workflow_dispatch: # 수동 실행 가능

jobs:
  crawl:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        cd python-crawler
        pip install -r requirements.txt
        
    - name: Run crawler with Bright Data Proxy
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
        # Bright Data API Configuration
        BRIGHT_DATA_API_KEY: ${{ secrets.BRIGHT_DATA_API_KEY }}
        # Bright Data Proxy Configuration (선택사항 - API 키가 있으면 자동 구성)
        BRIGHT_DATA_ENDPOINT: ${{ secrets.BRIGHT_DATA_ENDPOINT }}
        BRIGHT_DATA_USERNAME: ${{ secrets.BRIGHT_DATA_USERNAME }}
        BRIGHT_DATA_PASSWORD: ${{ secrets.BRIGHT_DATA_PASSWORD }}
        BRIGHT_DATA_SESSION_ID: ${{ secrets.BRIGHT_DATA_SESSION_ID }}
        BRIGHT_DATA_COUNTRY: ${{ secrets.BRIGHT_DATA_COUNTRY }}
        # Additional proxy endpoints (optional)
        BRIGHT_DATA_ENDPOINT_1: ${{ secrets.BRIGHT_DATA_ENDPOINT_1 }}
        BRIGHT_DATA_USERNAME_1: ${{ secrets.BRIGHT_DATA_USERNAME_1 }}
        BRIGHT_DATA_PASSWORD_1: ${{ secrets.BRIGHT_DATA_PASSWORD_1 }}
        BRIGHT_DATA_SESSION_ID_1: ${{ secrets.BRIGHT_DATA_SESSION_ID_1 }}
        BRIGHT_DATA_COUNTRY_1: ${{ secrets.BRIGHT_DATA_COUNTRY_1 }}
        BRIGHT_DATA_ENDPOINT_2: ${{ secrets.BRIGHT_DATA_ENDPOINT_2 }}
        BRIGHT_DATA_USERNAME_2: ${{ secrets.BRIGHT_DATA_USERNAME_2 }}
        BRIGHT_DATA_PASSWORD_2: ${{ secrets.BRIGHT_DATA_PASSWORD_2 }}
        BRIGHT_DATA_SESSION_ID_2: ${{ secrets.BRIGHT_DATA_SESSION_ID_2 }}
        BRIGHT_DATA_COUNTRY_2: ${{ secrets.BRIGHT_DATA_COUNTRY_2 }}
        # Crawler Configuration
        USE_BRIGHT_DATA_PROXY: true
        CRAWLER_MODE: tracked
        DEBUG_MODE: false
      run: |
        cd python-crawler
        python enhanced_naver_crawler.py
        
    - name: Notify completion
      if: always()
      run: |
        echo "Crawler job completed at $(date)"
        # 선택사항: Slack/Discord 알림 추가 가능